---
title: "NYC Taxi - Model Report"
author: "Kevin Putschko"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

# User Input
r_env <- "local"
input_model <- "2020-02-18"

# Set Up
knitr::opts_chunk$set(echo = FALSE)
pacman::p_load(tidyverse, lubridate, scales, leaflet, DT)
source("R/0_config.R")

script_config <- master_config %>% pluck(r_env)
script_config$input_model <- if (!is_empty(input_model)) input_model


# Load Summary
model_summary <- 
  file.path(script_config$filepath_models, script_config$input_model) %>% 
  dir(pattern = "summary", full.names = TRUE) %>% 
  read_rds()


# Load Runtimes
runtime_summary <- 
  script_config$filepath_logs %>% 
  dir(full.names = TRUE, pattern = ".csv") %>% 
  map_dfr(read_csv) %>% 
  distinct()


# Data Dates
display_rundate <- 
  runtime_summary %>% 
  filter(str_detect(action, "Fit Models"),
         timestamp == max(timestamp)) %>% 
  mutate(d_date = timestamp %>% date() %>% format("%d %b %Y"),
         d_time = runtime %>% number())

display_rows <- 
  model_summary$s_summary$n[[1]] %>% 
  number(big.mark = ",")

display_date_min <- model_summary$s_summary$date_min[[1]] %>% format("%b %Y")
display_date_max <- model_summary$s_summary$date_max[[1]] %>% format("%b %Y")
```


### Introduction

The models were refreshed on `r display_rundate$d_date[[1]]`.  

It took `r display_rundate$d_time[[1]]` seconds.

The data had `r display_rows` rows.

Table here:

```{r runtime_table}
runtime_summary %>% datatable()
```

### Data Exploration

Here it is...

```{r heatmap, fig.align='center'}
# calibri for headers
# avenir for body

model_summary$s_heatmap %>%
  ggplot(aes(x = pickup_hour, y = pickup_wday, fill = rides)) +
  geom_tile() +
  coord_equal() +
  scale_fill_viridis_c(label = number_format()) +
  labs(title = "New York City Taxi Rides", 
       subtitle = "Number of Taxi Rides by Hour and Weekday",
       fill = "Rides\nper Hour",
       x = "Hour of the Day",
       y = "Day of the Week",
       caption = str_glue("Data ranges from {display_date_min} to {display_date_max}")) +
  theme_gray()

model_summary$s_heatmap %>%
  ggplot(aes(x = pickup_hour, y = pickup_wday, fill = fpm)) +
  geom_tile() +
  coord_equal() +
  scale_fill_viridis_c(label = dollar_format()) +
  labs(title = "New York City Taxi Rides", 
       subtitle = "Average Fare per Mile by Hour and Weekday",
       fill = "Average Fare\nper Mile",
       x = "Hour of the Day",
       y = "Day of the Week",
       caption = str_glue("Data ranges from {display_date_min} to {display_date_max}")) +
  theme_gray()
```

### Map

This and that...

```{r clusters}
map_center <-
  model_summary$s_centers %>%
  summarise_at(vars(center_lon, center_lat), mean) %>%
  as.list()

model_summary$s_centers %>%
  leaflet(width = "100%") %>%
  addProviderTiles(providers$CartoDB.DarkMatterNoLabels, group = "New York City") %>%
  addCircles(lng = ~ center_lon,
             lat = ~ center_lat,
             label = ~str_c("Hub - ", taxi_hub),
             color = ~hub_color,
             stroke = TRUE,
             weight = 2,
             opacity = .60,
             fillColor = "transparent",
             radius = ~if_else(hub_pct > .20, 2500, 5000),
             group = "Hub Clusters") %>%
  addCircleMarkers(data = model_summary$s_blackmap,
                   lng = ~lon_r,
                   lat = ~lat_r,
                   opacity = ~log(n),
                   radius = ~log(n),
                   stroke = FALSE,
                   color = "yellow",
                   popup = NULL,
                   group = "Taxi Requests") %>%
  addLayersControl(overlayGroups = c("Taxi Requests", "Hub Clusters"),
                   options = layersControlOptions(collapsed = FALSE)) %>%
  hideGroup("Hub Clusters") %>%
  setView(lng = map_center$center_lon, lat = map_center$center_lat, zoom = 10)
```

